# Generated by Django 2.2.6 on 2019-10-24 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Nombre', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=60)),
                ('Correo', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('Contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=20)),
                ('Precio', models.CharField(max_length=8)),
                ('Descripcion', models.TextField()),
                ('Marca', models.CharField(max_length=20)),
                ('Imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('NombreTienda', models.CharField(max_length=40)),
                ('Rut_Tienda', models.EmailField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedore',
            fields=[
                ('RutVendedor', models.CharField(max_length=12)),
                ('NombreVendedor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('CorreoVendedor', models.EmailField(max_length=50)),
                ('Mensaje', models.TextField()),
                ('Tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BDTodoEstetica.Tienda')),
            ],
        ),
    ]
