# Generated by Django 2.2.6 on 2019-11-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDTodoEstetica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(upload_to='ImagenProductos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='NombreProducto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='Rut_Tienda',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
